# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from typing import Any, cast

from core import assistant_pb2 as assistant__pb2

assistant__pb2 = cast(Any, assistant__pb2)

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexText = channel.unary_unary(
                '/assistant.Assistant/IndexText',
                request_serializer=assistant__pb2.IndexRequest.SerializeToString,
                response_deserializer=assistant__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/assistant.Assistant/Query',
                request_serializer=assistant__pb2.QueryRequest.SerializeToString,
                response_deserializer=assistant__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Plan = channel.unary_unary(
                '/assistant.Assistant/Plan',
                request_serializer=assistant__pb2.PlanRequest.SerializeToString,
                response_deserializer=assistant__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/assistant.Assistant/ExecuteAction',
                request_serializer=assistant__pb2.Action.SerializeToString,
                response_deserializer=assistant__pb2.IndexResponse.FromString,
                _registered_method=True)


class AssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IndexText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Plan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Execute or simulate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexText': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexText,
                    request_deserializer=assistant__pb2.IndexRequest.FromString,
                    response_serializer=assistant__pb2.IndexResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=assistant__pb2.QueryRequest.FromString,
                    response_serializer=assistant__pb2.QueryResponse.SerializeToString,
            ),
            'Plan': grpc.unary_unary_rpc_method_handler(
                    servicer.Plan,
                    request_deserializer=assistant__pb2.PlanRequest.FromString,
                    response_serializer=assistant__pb2.PlanResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=assistant__pb2.Action.FromString,
                    response_serializer=assistant__pb2.IndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assistant.Assistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assistant.Assistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Assistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/IndexText',
            assistant__pb2.IndexRequest.SerializeToString,
            assistant__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/Query',
            assistant__pb2.QueryRequest.SerializeToString,
            assistant__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/Plan',
            assistant__pb2.PlanRequest.SerializeToString,
            assistant__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/ExecuteAction',
            assistant__pb2.Action.SerializeToString,
            assistant__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
