# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\x12\tassistant\"\x07\n\x05\x45mpty\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\t\"U\n\x0cIndexRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\n\n\x02ts\x18\x05 \x01(\x03\";\n\rIndexResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\"E\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\t\n\x01k\x18\x04 \x01(\x05\"7\n\x08QueryHit\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\">\n\rQueryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x04hits\x18\x02 \x03(\x0b\x32\x13.assistant.QueryHit\"T\n\x06\x41\x63tion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\tsensitive\x18\x03 \x01(\x08\x12\x18\n\x10preview_required\x18\x04 \x01(\x08\"8\n\x0bPlanRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04goal\x18\x03 \x01(\t\">\n\x0cPlanResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x11.assistant.Action2\xfe\x01\n\tAssistant\x12>\n\tIndexText\x12\x17.assistant.IndexRequest\x1a\x18.assistant.IndexResponse\x12:\n\x05Query\x12\x17.assistant.QueryRequest\x1a\x18.assistant.QueryResponse\x12\x37\n\x04Plan\x12\x16.assistant.PlanRequest\x1a\x17.assistant.PlanResponse\x12<\n\rExecuteAction\x12\x11.assistant.Action\x1a\x18.assistant.IndexResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_ID']._serialized_start=39
  _globals['_ID']._serialized_end=55
  _globals['_INDEXREQUEST']._serialized_start=57
  _globals['_INDEXREQUEST']._serialized_end=142
  _globals['_INDEXRESPONSE']._serialized_start=144
  _globals['_INDEXRESPONSE']._serialized_end=203
  _globals['_QUERYREQUEST']._serialized_start=205
  _globals['_QUERYREQUEST']._serialized_end=274
  _globals['_QUERYHIT']._serialized_start=276
  _globals['_QUERYHIT']._serialized_end=331
  _globals['_QUERYRESPONSE']._serialized_start=333
  _globals['_QUERYRESPONSE']._serialized_end=395
  _globals['_ACTION']._serialized_start=397
  _globals['_ACTION']._serialized_end=481
  _globals['_PLANREQUEST']._serialized_start=483
  _globals['_PLANREQUEST']._serialized_end=539
  _globals['_PLANRESPONSE']._serialized_start=541
  _globals['_PLANRESPONSE']._serialized_end=603
  _globals['_ASSISTANT']._serialized_start=606
  _globals['_ASSISTANT']._serialized_end=860
# @@protoc_insertion_point(module_scope)
